### ISSUE TITLE
Missing sample name error

### ISSUE THREAD

**Issue by marinawitherell** [nf-core/pathogensurveillance#15]
Deleted sample name of the first sample and got the error message:

ERROR ~ Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:INPUT_CHECK:SAMPLESHEET_CHECK (metadata_medium.csv)'

Pipeline would benefit from a more descriptive error message.

**Comment by zachary-foster** [comment]
This should be fixed now
