### ISSUE TITLE
Missing fastq1 error

### ISSUE THREAD

**Issue by marinawitherell** [nf-core/pathogensurveillance#16]
Deleted fastq1 (second column) of the first sample and got the error message:

ERROR ~ Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:INPUT_CHECK:SAMPLESHEET_CHECK (metadata_medium.csv)'

Pipeline would benefit from a more descriptive error message. Also note that this is different than having a file path that doesn't exist (including if special characters are in it). That error does have a descriptive error message.

**Comment by zachary-foster** [comment]
This should be fixed now
