### ISSUE TITLE
Missing fastq2 error

### ISSUE THREAD

**Issue by marinawitherell** [nf-core/pathogensurveillance#17]
Deleted fastq2 (third column) of the first sample and got the error message:

ERROR ~ Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:ASSIGN_REFERENCES:KHMER_TRIMLOWABUND (22-324_T1)'

This is interesting because the pipeline still ran for quit a bit of time with the first 5 processes completed and a few others. I deleted the fastq2 of the sample 22-299 but the one that resulted in the error was 22-324.

I ran this a second time to see if it was reproducible and got farther in the pipeline than I normally get even with no modification to the sample sheet input. This time I got the error message:

ERROR ~ Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:SPADES (22-330_T1)'

When I ran it a third time I got the same error message, but with the sample 22-324_T1.

**Comment by zachary-foster** [comment]
This should be fixed now
