### ISSUE TITLE
fastq1 and fastq2 file type error

### ISSUE THREAD

**Issue by marinawitherell** [nf-core/pathogensurveillance#18]
I deleted the .fastq.gz from the end of the fastq1 file name and then did the same for the fastq2. The error message that is printed is:

ERROR ~ Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:INPUT_CHECK:SAMPLESHEET_CHECK (metadata_medium.csv)'

There's a more descriptive message farther below that says:

Command error:
[CRITICAL] The FASTQ file has an unrecognized extension: test/data/reads/22-301_R2
It should be one of: .fq.gz, .fastq.gz On line 3.

This might be sufficient enough because I feel like it's pretty self explanatory, but it might be overwhelming for people that do not know how to read error messages. It is up to you whether to make it a more simple message.

**Comment by zachary-foster** [comment]
Yea, I think that error is good enough. I think we can leave it as it is. Thanks for checking though!
