### ISSUE TITLE
Check what happens when either the reference or reference_id columns are empty

### ISSUE THREAD

**Issue by zachary-foster** [nf-core/pathogensurveillance#22]
.. but the other is present.

If ID is missing, then the ID should be inferred from the reference file name.

**Comment by marinawitherell** [comment]
When the reference ID is missing then it does not disrupt the pipeline. This assumes that the ID is inferred from the reference file name. When the reference itself is missing, the pipeline errors out, but does not give a readable error. A more readable error should be given explaining that the reference is missing, but the reference ID is present.

**Comment by zachary-foster** [comment]
done
