### ISSUE TITLE
weird error when downloading genomes?

### ISSUE THREAD

**Issue by cahuparo** [nf-core/pathogensurveillance#27]
curl: (3) URL using bad/illegal format or missing URL
   ERROR:  curl command failed ( Sun Oct  8 04:11:28 PM PDT 2023 ) with: 3
  https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?query_key=1&WebEnv=MCID_6523371be8af48640e2d92e7&retstart=0&retmax=1580&db=taxonomy&rettype=uilist&retmode=text&tool=edirect&edirect=16.2&edirect_os=Linux&email=changlab%40fileserver%20has%20address%2010.206.67.17
  fileserver
   ERROR:  ELink failure
   ERROR:  Missing -db argument
   ERROR:  Missing -db argument

**Comment by zachary-foster** [comment]
Does this happen the same every time you rerun the pipeline?

**Comment by zachary-foster** [comment]
should be fixed by retry
