### ISSUE TITLE
Break up long reads into 150mers to enable long read data for variant calling 

### ISSUE THREAD

**Issue by zachary-foster** [nf-core/pathogensurveillance#40]
A collaborator has tested a lot of methods for variant calling with long read data and determined that breaking up reads into 150mers and using graphtyper works the best of the methods tested. This would be a easy way to accept long reads into the variant calling portion of the pipeline.

**Comment by masudermann** [comment]
Here is an example command for doing this:
`cat $infile | seqkit sliding -W 150 -s 150 -o ${strain}_nano150.fastq.gz`

**Comment by zachary-foster** [comment]
This has been implemented in the `dev` branch
