### ISSUE TITLE
If Spades or Bakta fail for small number of samples, is there a way to proceed without these samples?

### ISSUE THREAD

**Issue by masudermann** [nf-core/pathogensurveillance#51]
### Description of the bug

I have encountered this twice, with larger bacterial datasets, but for whatever reason, whether quality of raw read data is bad or spades cannot produce a decent assembly, Bakta will then fail (not surprisingly) and after a few retries, the whole pipeline stops until I remove the samples in question. 

Is there a way to proceed with the analysis, even if Spades, or Bakta fail for a small number of samples, making note of which samples couldn't go though the pipeline?

**Comment by zachary-foster** [comment]
Spades failures will now be ignored and any downstream steps relying on the assembly should be ignored. Feel free to reopen if this is still a problem.
