### ISSUE TITLE
Add option to delete or not publish intermendiate files 

### ISSUE THREAD

**Issue by zachary-foster** [nf-core/pathogensurveillance#63]
This would help avoid taking up lots of file space if that is a concern for the user

**Comment by logankblair** [comment]
nf-core plugin allowing for "automatic deletion of temporary files"
https://github.com/bentsherman/nf-boost

**Comment by logankblair** [comment]
There is also `publish_dir_mode` in the nextflow_schema.json
Right now it is set as `"default": "copy"` , but there are other choices

**Comment by zachary-foster** [comment]
This was done by Logan recently
