### ISSUE TITLE
Fail to create conda environment for sourmash_sketch

### ISSUE THREAD

**Issue by buchanri** [nf-core/pathogensurveillance#87]
After running the pipeline I got this error:
```
Caused by:
ERROR ~ Error executing process > 'PATHOGENSURVEILLANCE:SKETCH_COMPARISON:SOURMASH_SKETCH_READS (1)'

Caused by:
  Failed to create Conda environment
    command: mamba env create --prefix /nfs7/BPP/Chang_Lab/paradarc/paper3_bra/scripts/pathogensurveillance/work/conda/sourmash_sketch-481c3c545c778fa751538b4cac862f83 --file /nfs7/BPP/Chang_Lab/paradarc/paper3_bra/scripts/pathogensurveillance/./workflows/../subworkflows/local/../../modules/nf-core/sourmash/sketch/environment.yml
    status : 143
    message:
      Channels:
       - conda-forge
       - bioconda
       - defaults
      Platform: linux-64
      Collecting package metadata (repodata.json): ...working... done
      Solving environment: ...working... done



 -- Check '.nextflow.log' file for details
[89/34cffb] Submitted process > PATHOGENSURVEILLANCE:SKETCH_COMPARISON:SUBSET_READS (SZCCHNS3004)
-[nf-core/plantpathsurveil] Sent summary e-mail to buchanri@oregonstate.edu (sendmail)-
WARN: Access to undefined parameter `outdir` -- Initialise it to a default value eg. `params.outdir = some_value`
-[nf-core/plantpathsurveil] Pipeline completed with errors

 To clean the cache, run the command:
 nextflow clean wise_chandrasekhar -f

WARN: Killing running tasks (48)
```
I've tried `mamba clean --all` which has fixed conda environment issues in the past but this time it's not helping. I've also tried to remove the sourmash env it made (if it did make one) to force it to try and make the environment again to reinstall sourmash but no luck. Any ideas?

**Comment by zachary-foster** [comment]
This looks like one of those intermittent conda errors. Try deleting `/nfs7/BPP/Chang_Lab/paradarc/paper3_bra/scripts/pathogensurveillance/work/conda/sourmash_sketch-481c3c545c778fa751538b4cac862f83` and rerun.

**Comment by zachary-foster** [comment]
It looks like one of those intermittent conda errors. Normally I would do what you said, `mamba clean --all` and deleting `/nfs7/BPP/Chang_Lab/paradarc/paper3_bra/scripts/pathogensurveillance/work/conda/sourmash_sketch-481c3c545c778fa751538b4cac862f83`. I did see something about anaconda.org doing maintenance recently, so that could be the problem?
