### ISSUE TITLE
Error rendering report when I don't have core gene phylogeny (eukaryote dataset)

### ISSUE THREAD

**Issue by masudermann** [nf-core/pathogensurveillance#89]
### Description of the bug

I cannot render the report because I don't have a core gene phylogeny when I am working with a eukaryote-specific dataset. 

I successfully ran the pipeline with input dataset comprised of 20 P. pluvialis isolates. Report didn't render, so I proceeded to render report manually. It will render, but I need to first block out core gene phylogeny chunks. 

Do we need to revise the core gene phylo chunk or psminer function so it successfully renders either core gene or BUSCO tree? It could also be user error. 

Test dataset was: "_test_data/ppluvialis/ppluv_inputs"
### Command used and terminal output

```console

#Here is the error I get: 

processing file: index.qmd
  |...........................                   |  60% [unnamed-chunk-14]     Error in `core_plots[[1]]`:
! subscript out of bounds

Quitting from lines 284-290 [unnamed-chunk-14] (index.qmd)
                                                                                                                  
Execution halted
```

**Comment by zachary-foster** [comment]
The report does not yet use the busco trees, but I plan to add that in the next day or two. I will try out this dataset as I develop. Thanks!

**Comment by masudermann** [comment]
That makes sense!  In a similar vein, I am still getting with  my eukaryote tests when I don't have a POCP matrix as input into report. 

For pluvialis test, report intermediate files are here:

`pathogensurveillance/assets/main_report/_test_data/ppluvialis/ppluv_inputs`

I'm still working on optimizing reference parameters and will push some updated files shortly. With defaults, taxonomic classification was correct to the clade level, but not species level.

**Comment by zachary-foster** [comment]
This should be fixed by now
